events {}
http {
    server {
        listen 3000;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html; 

        location / {
            try_files $uri /index.html =404;
        }

        # Serve a static /metrics file if you want Prometheus to scrape something
        location = /metrics {
            default_type text/plain;
            alias /usr/share/nginx/html/metrics;
        }
    }
}